### ISSUE TITLE
troubles with nimqt

### ISSUE THREAD

**Issue by grd** [jerous86/nimqt#33]
Hi, I am using VSCode to write (and it works rather well) but I have to say that IMO  your library is rather complicated to understand. For instance when I run the code with `nim cpp -r import_file.nim` in https://github.com/grd/FreePDM-Client it can't find the connections.

Is there also a different platform to discuss this kind of issues instead of writing new issues in github?

Best regards, Gerard

**Comment by jerous86** [comment]
The library tries to map closely to Qt. The possible deviations are there probably due to the fact that there is a lot of custom c++ generated behind the scenes, which make it sometimes difficult to do otherwise.
Feel free to suggest improvements.

Regarding your issue.
E.g. `connect(buttonBox, SIGNAL "accepted()", rootWg, SLOT "apply_file()")`
tries to connect to a slot `apply_file` for the object `rootWg` (of type `ptr QDialog`). However, there is no slot `apply_file` defined for `rootWg` -- you defined it to be just a proc.
To define a slot, you need to define your own object, which inherits from e.g. `QObject`, and then you'll have to define slots within that object. (This is just like in Qt.) You can check `examples/hello.nim` for a basic example.

I see there is a tab called "Discussions", maybe you can use that to discuss these issues?

**Comment by grd** [comment]
No sorry, I don't have any improvements. I come from the Python front, but I dislike Python, mostly because of the lack of types but Python has many more serious issues and I dislike C++ a lot more because of its verbosity and its complicated history.

I already figured out a lot because I read the examples and other pieces of the library code too. 

Anyway thanks for the reply! I am closing the issue now.
